### ISSUE TITLE
人数分順位をつけてくれないことがある

### ISSUE THREAD

**Issue by yfujii01** [takayamazusa/lottery#1]
@takayamazusa 
```
全体の数は何人ですか？
50
50人の中から当たりは何人ですか？
20
1等　34番
2等　37番
3等　28番
4等　16番
5等　44番
6等　36番
7等　43番
8等　50番
9等　22番
10等　13番
11等　41番
12等　10番
13等　14番
14等　27番
15等　23番
```
20番まで順位をつけてほしいのに15等までしか付けてくれませんでした。

**Comment by takayamazusa** [comment]
@yfujii01 
3bd42ca5f4ed8b15360052007258cf9ad8784435
求める人数分順位が出るよう、修正しました。

**Comment by yfujii01** [comment]
@takayamazusa 
求めていた動きが実装されたと思いますのでcloseします。

できたら↓も考えてみてください。
------
今は「ランダムで得た数値が重複した場合は処理を繰り返し続ける仕様」のため母数と当たり数を増やした場合に繰り返し処理が大量に発生し、結構な処理時間がかかるようになっています。

例えば「母数分の配列を用意しランダムにソート、その結果の上から順番に順位とする」ようにすればもう少し速くなるかなと思います。
